steps:
  # Install node dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    id: 'npm-install'
    
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '--build-arg', 'BACKEND_URL=${_BACKEND_URL}',
           '-t', 'gcr.io/$PROJECT_ID/neufin-frontend:$COMMIT_SHA', 
           '-t', 'gcr.io/$PROJECT_ID/neufin-frontend:latest', 
           '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin-frontend:$COMMIT_SHA']
    
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin-frontend:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'neufin-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/neufin-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'PORT=8080,BACKEND_URL=${_BACKEND_URL},VITE_GA_MEASUREMENT_ID=${_VITE_GA_MEASUREMENT_ID},VITE_STRIPE_PUBLIC_KEY=${_VITE_STRIPE_PUBLIC_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/neufin-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/neufin-frontend:latest'
  
timeout: '1600s'

substitutions:
  _VITE_GA_MEASUREMENT_ID: 'G-SXSDL3YRVN' # Google Analytics Measurement ID
  _VITE_STRIPE_PUBLIC_KEY: '' # Set this in Cloud Build trigger
  _BACKEND_URL: 'https://neufin-backend-[your-project-hash]-uc.a.run.app' # Update with your actual backend URL

options:
  machineType: 'E2_HIGHCPU_8'
  env:
    - 'NODE_ENV=production'