steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '-t', 'gcr.io/$PROJECT_ID/neufin-backend:$COMMIT_SHA', 
           '-t', 'gcr.io/$PROJECT_ID/neufin-backend:latest', 
           './backend']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin-backend:$COMMIT_SHA']
    
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin-backend:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'neufin-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/neufin-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'PORT=8080,ALPHA_VANTAGE_API_KEY=${_ALPHA_VANTAGE_API_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/neufin-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/neufin-backend:latest'
  
timeout: '1200s'

substitutions:
  _ALPHA_VANTAGE_API_KEY: '' # Set this in Cloud Build trigger
  _OPENAI_API_KEY: '' # Set this in Cloud Build trigger
  _ANTHROPIC_API_KEY: '' # Set this in Cloud Build trigger
  _STRIPE_SECRET_KEY: '' # Set this in Cloud Build trigger

options:
  machineType: 'E2_HIGHCPU_8'