steps:
  # Install node dependencies and build
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    id: 'npm-install'
    
  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    id: 'npm-build'
    
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '--cache-from', 'gcr.io/$PROJECT_ID/neufin:latest',
           '-t', 'gcr.io/$PROJECT_ID/neufin:$COMMIT_SHA', 
           '-t', 'gcr.io/$PROJECT_ID/neufin:latest', 
           '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin:$COMMIT_SHA']
    
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/neufin:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'neufin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/neufin:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'PORT=8080,VITE_GA_MEASUREMENT_ID=${_VITE_GA_MEASUREMENT_ID},VITE_STRIPE_PUBLIC_KEY=${_VITE_STRIPE_PUBLIC_KEY},NEUFIN_BACKEND_URL=${_NEUFIN_BACKEND_URL}'

images:
  - 'gcr.io/$PROJECT_ID/neufin:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/neufin:latest'
  
timeout: '1600s'

substitutions:
  _VITE_GA_MEASUREMENT_ID: 'G-SXSDL3YRVN' # Google Analytics Measurement ID
  _VITE_STRIPE_PUBLIC_KEY: '' # Set this in Cloud Build trigger
  _NEUFIN_BACKEND_URL: 'https://neufin-backend-abcdef123-uc.a.run.app' # Update with your backend URL

options:
  machineType: 'E2_HIGHCPU_8'
  env:
    - 'NODE_ENV=production'